# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca514b13a0ed6f7ab754d708310273f8da150dc099d9e30f255ceee41883aabdd3014d258f095e41f3a8caf226b93722797a5b633f6e2b14af82085476794409

test:
  secret_key_base: e8fab364adafe7007673b1ddf09b17206e2cd08e90d6aefff6eb5e4a84c798f2a924821e292eda96080d92bbf97f72fe5ec7649706053c1ece7d4e1b7ae2aeaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
